### ISSUE TITLE
'.zshrc' could not be updated

### ISSUE THREAD

**Issue by dhruvdutt** [mklement0/n-install#14] opened 2017-07-04 13:45 UTC
```
-- Running local n installation to '/home/dhruvdutt/n/bin'...
main: line 333: /home/dhruvdutt/.zshrc: Permission denied
Aborting, because shell initialization file '/home/dhruvdutt/.zshrc' could not be updated.
n-install: ERROR: ABORTING due to unexpected error.
```

**Comment by mklement0** [comment] 2017-07-04 14:16
Sounds like a permissions problem with your `~/.zshrc` file. Make sure that you have write permissions and try again.

**Comment by mklement0** [comment] 2017-07-04 21:31
I'm closing this, because it sounds like the issue is unrelated to n-install.

If it turns out it is, after all, we can reopen.

**Closed by mklement0** 2017-07-04 21:31 UTC

**Comment by dhruvdutt** [comment] 2017-07-05 06:49
Got messed up with many files on permissions. Fixed everything and through. Thanks!
