### ISSUE TITLE
Installation breaks `n`'s symlinks/etc. on macOS

### ISSUE THREAD

**Issue by isiahmeadows** [mklement0/n-install#13] opened 2017-05-11 04:40 UTC
See tj/n#436 for more details.

**Comment by mklement0** [comment] 2017-05-11 05:10
I'm afraid I don't understand the description in the linked issue.

Do you have a Node.js installation _alongside_ the `n`-managed version?

Such a setup isn't supported, and the installer should refuse installation if a preexisting `n` / Node.js installation is found.

However, there's nothing that can prevent a manual installation of Node.js _later_.

If indeed you're trying to use a manual Node.js installation alongside `n`-managed ones: what is the use case for that?

**Comment by mklement0** [comment] 2017-05-11 12:30
Note that the whole point of creating `n-install` was so that you _wouldn't_ have to manually install Node.js - see http://stackoverflow.com/a/30967671/45375

**Comment by isiahmeadows** [comment] 2017-05-11 14:28
@mklement0 

In my case, I didn't have such an installation alongside this. The linked issue was a proposed fix that would account for and allow that, but my issue was that `n` wasn't finding its own managed versions.

**Comment by mklement0** [comment] 2017-05-11 14:31
Then I still don't understand the cause of the problem and how n-install comes into play.

**Comment by isiahmeadows** [comment] 2017-05-11 16:08
BTW, I've already uninstalled it from here and installed it from `npm`, so I'm okay now.

**Comment by mklement0** [comment] 2017-05-11 17:47
I'm glad to hear it, so I'll close this issue.

I'm still curious about your use case and what actually happened.

If you feel that something of general interest could be done in this context to improve in n-install, do let me know.

Would simply putting `$N_PREFIX/bin` _first_ in the `$PATH` have solved your problem?

**Closed by mklement0** 2017-05-11 17:47 UTC
